[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.12"

[features]
seeds = false
skip-lint = true

[registry]
url = "https://api.apr.dev"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[provider]
cluster = "localnet"
wallet = ".secrets/admin.json"

[programs.localnet]
messenger = "CGRAmxwrfg86KGaPJ3jD1ePgpebP6UJwSUHVZ1UQs78q"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.mainnet-beta.solana.com"
