[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[provider]
cluster = "localnet"
wallet = "/Users/tiamo/.config/solana/id.json"

[programs.localnet]
messenger = "6RSutwAoRcQPAMwyxZdNeG76fdAxzhgxkCJXpqKCBPdm"
