[workspace]
resolver = "2"
members = [
  "programs/*",
]

[profile.release]
lto = "fat"
codegen-units = 1
overflow-checks = true
# opt-level = "z"

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
